name: "Run unit tests"

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make clang-12 llvm llvm-12 linux-headers-$(uname -r)

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Compile eBPF programs
        run: |
          make -C ebpf

      - name: Run unit tests
        run: |
          go test -v ./...
